### ISSUE TITLE
get_build_logs(follow=False) returns string with dicts

### ISSUE THREAD

**Issue by pbabinca** [projectatomic/osbs-client#128] opened 2015-06-10 12:28 UTC
I'm using similar code to this:
```python
from osbs.api import OSBS
from osbs.conf import Configuration

os_conf = Configuration()
build_conf = Configuration()
osbs = OSBS(os_conf, build_conf)
build_response = osbs.create_build(
    git_uri=git_uri,
    git_ref=scm.revision,
    user=owner_name,
    component=component,
    target=koji_target,
    architecture=arch
)
build_id = build_response.build_id
build_log_contents = osbs.get_build_logs(build_id)
outfile = open('build.log', 'w')
outfile.write(build_log_contents)
outfile.close()
```
First lines of `build.log` looks like this:
```
{"stream":"Step 0 : FROM b1582e9358a36e1e4687543471877f324bd0f3705e5b176c3e1ab5644606763d\n"}

{"stream":" ---\u003e b1582e9358a3\n"}

{"stream":" ---\u003e Running in d6416c23a140\n"}

{"stream":" ---\u003e 00a9aeb52282\n"}

{"stream":"Removing intermediate container d6416c23a140\n"}

{"stream":"Step 1 : ADD dock-repos/* '/etc/yum.repos.d/'\n"}

{"stream":" ---\u003e affb94fced82\n"}
```
I don't think dicts should be there but actual content instead.

**Comment by TomasTomecek** [comment] 2015-06-10 12:41
This is the stuff which `docker logs` produces. dock parses it during build and logs processed messages but stores raw version in metadata of a build

**Comment by mmilata** [comment] 2015-10-27 16:00
Duplicate of #72?

**Comment by twaugh** [comment] 2015-10-27 16:01
Yes, agreed.

**Closed by twaugh** 2015-10-27 16:01 UTC
